pTMR_cols = ['bmi', 'age_amputation', 'gender_Male', 'alcoholism_Yes', 'smoking_Yes',
       'opioid_use_preop_Yes', 'neurop_pain_med_use_prepo_Yes', 'diabetes_Yes',
       'hypothyroidism_Yes', 'depression_Yes', 'anxiety_Yes', 'ptsd_Yes',
       'per_vasc_disease_Yes', 'ckd_Yes', 'hx_chronic_pain_Yes', 'crps_Yes',
       'distal_proximal_proximal', 'indication_amputation_Dysfunctional',
       'indication_amputation_Infection or Sepsis',
       'indication_amputation_Malignancy',
       'indication_amputation_Peripheral Vascular Disease',
       'indication_amputation_Trauma']

sTMR_cols = ['bmi', 'time_amptmr_years', 'age_amputation', 'age_ican_surgery',
       'preop_score', 'gender_Male', 'alcoholism_Yes', 'smoking_Yes',
       'opioid_use_preop_Yes', 'neurop_pain_med_use_prepo_Yes', 'diabetes_Yes',
       'hypothyroidism_Yes', 'depression_Yes', 'anxiety_Yes', 'ptsd_Yes',
       'per_vasc_disease_Yes', 'ckd_Yes', 'hx_chronic_pain_Yes', 'crps_Yes',
       'distal_proximal_proximal', 'indication_amputation_Infection or Sepsis',
       'indication_amputation_Malignancy',
       'indication_amputation_Peripheral Vascular Disease',
       'indication_amputation_Trauma']

combined_cols = ['bmi', 'age_amputation', 'gender_Male', 'alcoholism_Yes', 'smoking_Yes',
       'opioid_use_preop_Yes', 'neurop_pain_med_use_prepo_Yes', 'diabetes_Yes',
       'hypothyroidism_Yes', 'depression_Yes', 'anxiety_Yes', 'ptsd_Yes',
       'per_vasc_disease_Yes', 'ckd_Yes', 'hx_chronic_pain_Yes', 'crps_Yes',
       'distal_proximal_proximal', 'indication_amputation_Dysfunctional',
       'indication_amputation_Infection or Sepsis',
       'indication_amputation_Malignancy',
       'indication_amputation_Peripheral Vascular Disease',
       'indication_amputation_Trauma', 'time_amptmr_years', 'age_ican_surgery',
         'preop_score']

combined_cols_dict = {
    'bmi': 'BMI',
    'age_amputation': 'Age, at time of amputation',
    'gender_Male': 'Sex, Male',
    'alcoholism_Yes': 'Alcoholism',
    'smoking_Yes': 'Smoking',
    'opioid_use_preop_Yes': 'Opioid use, preop',
    'neurop_pain_med_use_prepo_Yes': 'Neuromodulator use, preop',
    'diabetes_Yes': 'Diabetes',
    'hypothyroidism_Yes': 'Hypothyroidism',
    'depression_Yes': 'Depression',
    'anxiety_Yes': 'Anxiety',
    'ptsd_Yes': 'PTSD',
    'per_vasc_disease_Yes': 'PVD',
    'ckd_Yes': 'CKD',
    'hx_chronic_pain_Yes': 'History of Chronic Pain',
    'crps_Yes': 'CRPS',
    'distal_proximal_proximal': 'Amputation level, proximal',
    'indication_amputation_Dysfunctional': 'Amputation indication, Dysfunctional',
    'indication_amputation_Infection or Sepsis': 'Amputation indication, Infection or Sepsis',
    'indication_amputation_Malignancy': 'Amputation indication, Malignancy',
    'indication_amputation_Peripheral Vascular Disease': 'Amputation indication, Peripheral Vascular Disease',
    'indication_amputation_Trauma': 'Amputation indication, Trauma',
    'time_amptmr_years': 'Intervel: amputation to TMR',
    'age_ican_surgery': 'Age, at time of TMR',
    'preop_score': 'Pain score, preop'
}